### ISSUE TITLE
nested_under and see_instead interaction

### ISSUE THREAD

**Issue by gdamore** [daviddrysdale/mdbook-indexing#4]
I have a document where I want to achieve an index that looks like:

```
PAIR, see protocol, PAIR
... other entries..
protocol,
   PAIR,
```

I've come up with a hack but I think it would be better if you could add more formal support for it.

Essentially, I'm using &zwj; to create fake index entries like this:

```
[preprocessor.indexing.see_instead]
"_PAIR_&zwj;" = "protocol, _PAIR_"

[preprocessor.indexing.nest_under]
"_PAIR_" = "protocol"
```

Anyway, maybe you could make this a little nicer somehow?

**Comment by gdamore** [comment]
Alternatively, if I had a way to specify the nesting, such as:

{{ni:protocol:_PAIR_}}

(I assume we'd want hni and maybe nii variants as well?)  this would help.  Or possibly just treat commas in the index as nesting terms?  Although not everyone might want that.

**Comment by daviddrysdale** [comment]
I've generally done this by including repetition in the sub-entries:
```
[preprocessor.indexing.see_instead]
"PAIR" = "protocol, PAIR"

[preprocessor.indexing.nest_under]
"protocol, PAIR" = "protocol"
```
giving:
```
PAIR, see protocol, PAIR
protocol, 1
      protocol, PAIR, 1
      protocol, PUSH, 1
PUSH, see protocol, PUSH
```
but the repetition/redundancy isn't ideal.

One possible approach might be to remove leading `"<head>, "` text from any subentry, if the text before the comma matches the head entry.  That should result in:
```
PAIR, see protocol, PAIR
protocol, 1
      PAIR, 1
      PUSH, 1
PUSH, see protocol, PUSH
```

(That's probably a smaller/easier change than specifying nesting at the index point, although explicit nesting might be closer to other indexing systems, e.g. [AsciiDoc](https://docs.asciidoctor.org/asciidoc/latest/sections/user-index/#index-terms).)

**Comment by daviddrysdale** [comment]
I've put in #6 as something that should hopefully work in the short term, and raised #14 for re-thinking nesting support in general.
